### ISSUE TITLE
Get your json.el patches merged upstream

### ISSUE THREAD

**Issue by tarsius** [TaylanUB/json-sexp-mode#1]
You should get your changes to `json.el` merged upstream. Your package depends on the patched versions, other packages might depend on the changes that have been made to the upstream version since you forked. These packages cannot be used at the same time.

**Comment by TaylanUB** [comment]
Jonas Bernoulli notifications@github.com writes:

> You should get your changes to json.el merged upstream. Your package
> depends on the patched versions, other packages might depend on the
> changes that have been made to the upstream version since you forked.
> These packages cannot be used at the same time.

I quit emacs-devel shortly after joining it and don't feel like
returning yet.  I did my FSF copyright assignment though so maybe
someone else can try to get the patch through.

I'll merge upstream changes to the json.el in the repo when I have time,
maybe later today.

Taylan

**Comment by TaylanUB** [comment]
I just ditched the modified json.el in favor of a much more customized `jsxp.el`.

This removes a lot of (IMO unneeded) flexibility, and alleviates the need of upstream cooperation, turns JSON objects into quasi-alists like `((k1 v1) (k2 v2))` (no dots) so it's nicer to read and write, and maybe makes things a bit more efficient, though the sexpr pretty-printing seems to dominate so it might be a minor or negligible gain...

**Comment by tarsius** [comment]
Thanks!

**Comment by TaylanUB** [comment]
Sorry that it took so long. :-)
